######################################################################
# Automatically generated by qmake (3.1) Wed Dec 15 14:43:41 2021
######################################################################

TEMPLATE= subdirs
TARGET = qwidget
# Directories
SUBDIRS += qmake
